DATA_DIR: '/hdfs/resrchvc/v-bojian/data' 
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: DetMsNet.DetMsNet75_stage4_body
  FASTER_RCNN: True
NUM_GPUS: 4
MSNET:
  MSNET_ON: True
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/triangle_32_3143.pth.tar'
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
RPN:
  STRIDE: 4
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
